### GET quiz scores
GET localhost:6969/api/quiz
Accept: application/json

### Send quiz scores
POST localhost:6969/api/quiz
Content-Type: application/json

{
  "currentScore": 69,
  "userId": "656a4d7a48b8f541822c0f37",
  "date": "2023-10-10"
}